- use __func__, instead of __FUNCTION__ when available. - detect the availability by autoconf

diff --git a/kame/kame/dhcp6/configure b/kame/kame/dhcp6/configure
--- a/kame/kame/dhcp6/configure
+++ b/kame/kame/dhcp6/configure
@@ -3617,26 +3617,117 @@ fi;
 echo "$as_me:3617: result: $enableval" >&5
 echo "${ECHO_T}$enableval" >&6;
 
+echo "$as_me:3620: checking ANSI predeclared __func__" >&5
+echo $ECHO_N "checking ANSI predeclared __func__... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line 3623 "configure"
+#include "confdefs.h"
+
+int
+main ()
+{
+void func(void) {printf("%s\n", __func__);}
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:3635: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:3638: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:3641: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:3644: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:3646: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	 pred_func_id=ansi
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:3652: result: no" >&5
+echo "${ECHO_T}no" >&6
+	 pred_func_id=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+if test $pred_func_id = no; then
+echo "$as_me:3658: checking gcc predelcared __FUNCTION__" >&5
+echo $ECHO_N "checking gcc predelcared __FUNCTION__... $ECHO_C" >&6
+	cat >conftest.$ac_ext <<_ACEOF
+#line 3661 "configure"
+#include "confdefs.h"
+
+int
+main ()
+{
+void func(void) {printf("%s\n", __FUNCTION__);}
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:3673: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:3676: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:3679: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:3682: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:3684: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+		 pred_func_id=gcc
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+echo "$as_me:3690: result: no" >&5
+echo "${ECHO_T}no" >&6
+		 pred_func_id=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+case $pred_func_id in
+	ansi)
+		cat >>confdefs.h <<\EOF
+#define HAVE_ANSI_FUNC 1
+EOF
+
+		;;
+	gcc)
+		cat >>confdefs.h <<\EOF
+#define HAVE_GCC_FUNCTION 1
+EOF
+
+		;;
+esac
+
 for ac_header in stdarg.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
-echo "$as_me:3623: checking for $ac_header" >&5
+echo "$as_me:3714: checking for $ac_header" >&5
 echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 3629 "configure"
+#line 3720 "configure"
 #include "confdefs.h"
 #include <$ac_header>
 _ACEOF
-if { (eval echo "$as_me:3633: \"$ac_cpp conftest.$ac_ext\"") >&5
+if { (eval echo "$as_me:3724: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
   ac_status=$?
   egrep -v '^ *\+' conftest.er1 >conftest.err
   rm -f conftest.er1
   cat conftest.err >&5
-  echo "$as_me:3639: \$? = $ac_status" >&5
+  echo "$as_me:3730: \$? = $ac_status" >&5
   (exit $ac_status); } >/dev/null; then
   if test -s conftest.err; then
     ac_cpp_err=$ac_c_preproc_warn_flag
@@ -3655,7 +3746,7 @@ else
 fi
 rm -f conftest.err conftest.$ac_ext
 fi
-echo "$as_me:3658: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "$as_me:3749: result: `eval echo '${'$as_ac_Header'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
 if test `eval echo '${'$as_ac_Header'}'` = yes; then
   cat >>confdefs.h <<EOF
@@ -3775,7 +3866,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:3778: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:3869: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -3943,7 +4034,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:3946: error: ambiguous option: $1
+    { { echo "$as_me:4037: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3962,7 +4053,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:3965: error: unrecognized option: $1
+  -*) { { echo "$as_me:4056: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3998,7 +4089,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
-  *) { { echo "$as_me:4001: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4092: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4205,7 +4296,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4208: creating $ac_file" >&5
+    { echo "$as_me:4299: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4223,7 +4314,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4226: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4317: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4236,7 +4327,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4239: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4330: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
